- name: Lanzar una instancia EC2 en AWS
  hosts: localhost
  connection: local #no requiere conección ssh
  gather_facts: False #se desactiva la recolección de facs, no se ejecuta en maquina remota
  vars:
    aws_region: "us-east-1" #Region donde se lanzara la instancia
    security_group_name: "blockstellart-sg" #Nombre del grupo de seguridad
    aws_vpc_id: "vpc-05447e117e1265176"
    aws_image_id: "ami-0f8a61b66d1accaee"
  tasks:
    - name: Crear grupo seguridad para EC2
      amazon.aws.ec2_group:
        name: {{security_group_name}}
        description: "Grupo de seguridad para EC2 con acceso SSH, HTTP, HTTPS"
        region: {{aws_region}}
        vpc_id: {{aws_vpc_id}}
        rules:
          - proto: tcp
            ports:
              - 22 #SSH
              - 80 #HTTP
              - 443 #HTTPS
            cidr_ip: 0.0.0.0/0 #direcciones IP que se estan permitiendo
      register: sg_info #variable que almacena la informacion del grupo de seguridad creado

    - name: Mostar el ID del grupo de seguridad creado
      debug:
        msg: "ID de grupo de seguridad es: {{sg_info.group_id}}"

    - name: Crear una nueva instancia EC2
      amazon.aws.ec2_instance: #modulo que permite crear instancias EC2
        name: "servidor-blockstellart"
        key_name: "ansible_key" #clave ssh para acceder a la instancia
        instance_type: t2.micro #tipo de instancia
        security_group: {{security_group_name}} #Grupo de seguridad para EC2
        image_id: {{aws_image_id}} #ID de la imagen AMI
        region: {{aws_region}} #Region donde se lanzara la instancia
        state: running #Estado de la instancia
      register: ec2_info #variable que almacena la informacion de la instancia creada

    - name: Mostar informacion de la EC2
      debug:
        msg: "La IP publica de la instancia es: {{ec2_info.instances[0].public_ip_address}}" #Muestra la IP publica de la instancia con la información de la Instancia
      